CREATE DATABASE  repaso;
USE repaso;
CREATE TABLE categorias (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL
);
CREATE TABLE marcas (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL
);

CREATE TABLE productos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	categoria INT NOT NULL,
	marca INT(10) NOT NULL,
	nombre VARCHAR(255) NOT NULL,
	existencias INT(10) NOT NULL,
	FOREIGN KEY (categoria) REFERENCES categorias(Id) ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY (marca) REFERENCES marcas(id) ON UPDATE NO ACTION ON DELETE CASCADE
)